services:
  eroxii-landing:
    build: .
    container_name: eroxii-landing
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - alpha_network

networks:
  alpha_network:
    external: true
